/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleLib */

#ifndef _Included_SampleLib
#define _Included_SampleLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SampleLib
 * Method:    soma
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_SampleLib_soma
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
